# Generated by Django 3.2.13 on 2023-01-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cell',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
