# Generated by Django 3.2.13 on 2023-01-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_leader',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
